#!/bin/bash

if ((EUID != 0)); then
  exec sudo "$0"
fi

set -euxo pipefail

rm -rf .rootfs
debootstrap --include="$(paste -sd , packages)" bullseye .rootfs
cp -RT rootfs .rootfs
(cd .rootfs && bsdtar -Jc *) | pv > drop.tar.xz
